# Generated by Django 4.2.7 on 2023-11-23 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addvehicle',
            name='parking_area_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParkingManagement.category'),
        ),
    ]
